### ISSUE TITLE
Prepare release 2.3.0

### ISSUE THREAD

**Issue by mundschenk-at** [mundschenk-at/avatar-privacy#122]
- [x] Decide whether the version should be 2.3.0 or 3.0.0.
- [x] Decide whether WordPress 5.2 will be required.
- [x] Clean up README.
- [x] Clean up CHANGELOG.
